//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public Nullable<int> post_id { get; set; }
        public string content { get; set; }
        public Nullable<decimal> price { get; set; }
        public string PMs_name { get; set; }
        public Nullable<int> PMs_id { get; set; }
    
        public virtual PM PM { get; set; }
        public virtual post post { get; set; }
    }
}
