//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM
    {
        public PM()
        {
            this.comments = new HashSet<comment>();
            this.feedbacks = new HashSet<feedback>();
            this.requests = new HashSet<request>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string qualfications { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
