//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.feedbacks = new HashSet<feedback>();
            this.requests = new HashSet<request>();
            this.teams = new HashSet<team>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int state { get; set; }
        public string price { get; set; }
        public string project_remove { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<team> teams { get; set; }
    }
}
