//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.posts = new HashSet<post>();
            this.requests = new HashSet<request>();
            this.teams = new HashSet<team>();
        }
    
        public int id { get; set; }
        public int type_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string job { get; set; }
        public byte[] photo { get; set; }
    
        public virtual JD JD { get; set; }
        public virtual PM PM { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<team> teams { get; set; }
        public virtual TL TL { get; set; }
        public virtual type type { get; set; }
    }
}
