//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int id { get; set; }
        public int rate { get; set; }
        public string content { get; set; }
        public int PM_id { get; set; }
        public int TL_id { get; set; }
        public int JD_id { get; set; }
        public int project_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual JD JD { get; set; }
        public virtual PM PM { get; set; }
        public virtual project project { get; set; }
        public virtual TL TL { get; set; }
    }
}
