//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestProject
    {
        public int id { get; set; }
        public int post_id { get; set; }
        public string content { get; set; }
        public decimal price { get; set; }
        public int PMs_id { get; set; }
        public System.DateTime duration { get; set; }
    
        public virtual PM PM { get; set; }
        public virtual post post { get; set; }
    }
}
